CREATE DATABASE IF NOT EXISTS cuentaBancaria;
USE cuentaBancaria;
CREATE TABLE cuentas_bancarias (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  saldo INT NOT NULL,
  activo BOOLEAN NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
